#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.

import re
import logging
import smtplib
import email.parser
import ipaddress
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import header
from email.message import EmailMessage

import idna
import six
import tg
from paste.deploy.converters import asbool, asint, aslist
from formencode import validators as fev
from tg import tmpl_context as c
from tg import app_globals as g

from allura.lib.utils import ConfigProxy
from allura.lib import exceptions as exc
from allura.lib import helpers as h

log = logging.getLogger(__name__)

RE_MESSAGE_ID = re.compile(r'<(?:[^>]*/)?([^>]*)>')
config = ConfigProxy(
    common_suffix='forgemail.domain',
    common_suffix_alt='forgemail.domain.alternates',
    return_path='forgemail.return_path',
    sender_authentication_mode='forgemail.sender_authentication.mode',
    sender_authentication_authserv_id='forgemail.sender_authentication.authserv_id',
    sender_authentication_trusted_relay_networks=(
        'forgemail.sender_authentication.trusted_relay_networks'),
)
EMAIL_VALIDATOR = fev.Email(not_empty=True)

# http://www.jebriggs.com/blog/2010/07/smtp-maximum-line-lengths/
MAX_MAIL_LINE_OCTETS = 990
MAX_AUTHENTICATION_RESULTS_OCTETS = 16 * 1024
MAX_FROM_HEADER_OCTETS = 2 * 1024
MAX_AUTHENTICATION_RESULTS_CLAUSES = 64
MAX_AUTHENTICATION_RESULTS_COMMENT_DEPTH = 8

RE_TARGET_AUTHENTICATION_METHOD = re.compile(
    r'(?ai)\A(dmarc|spf)(?=[^a-z0-9-]|\Z)')
RE_DMARC_RESULT = re.compile(
    r'(?a)\Admarc=([a-z][a-z0-9-]*)[ \t]+'
    r'header\.from=([^\s()<>@,;:=/"\\]+)\Z')
RE_SPF_RESULT = re.compile(
    r'(?a)\Aspf=([a-z][a-z0-9-]*)[ \t]+'
    r'smtp\.mailfrom=([^\s()<>@,;:=/"\\]+)\Z')

email_policy = email.policy.SMTP + email.policy.strict


def Header(text, *more_text) -> str:
    '''
    Helper to make sure we encode headers properly
    This used to return an email.header.Header instance
    But needs to be a plain str now that we're using email.policy.SMTP
    '''
    if isinstance(text, header.Header):
        return str(text)

    if not isinstance(text, str):
        raise TypeError('This must be unicode: %r' % text)

    hdr_text = text
    for m in more_text:
        if not isinstance(m, str):
            raise TypeError('This must be unicode: %r' % text)
        hdr_text += ' ' + m
    return hdr_text


def AddrHeader(fromaddr) -> str:
    '''Accepts any of:
        Header() instance
        foo@bar.com
        "Foo Bar" <foo@bar.com>
    '''
    if isinstance(fromaddr, str) and ' <' in fromaddr:
        name, addr = fromaddr.rsplit(' <', 1)
        addr = '<' + addr  # restore the char we just split off
        addrheader = Header(name, addr)
        if str(addrheader).startswith('=?'):  # encoding escape chars
            # then quoting the name is no longer necessary
            name = name.strip('"')
            addrheader = Header(name, addr)
    else:
        addrheader = Header(fromaddr)
    return addrheader


def is_autoreply(msg):
    '''Returns True, if message is an autoreply

    Detection based on suggestions from
    https://github.com/opennorth/multi_mail/wiki/Detecting-autoresponders
    '''
    h = msg['headers']
    return (
        h.get('Auto-Submitted') == 'auto-replied'
        or h.get('X-POST-MessageClass') == '9; Autoresponder'
        or h.get('Delivered-To') == 'Autoresponder'
        or h.get('X-FC-MachineGenerated') == 'true'
        or h.get('X-AutoReply-From') is not None
        or h.get('X-Autogenerated') in ['Forward', 'Group', 'Letter', 'Mirror', 'Redirect', 'Reply']
        or h.get('X-Precedence') == 'auto_reply'
        or h.get('Return-Path') == '<>'
    )


def parse_address(addr):
    userpart, domain = addr.split('@')
    # remove common domain suffix
    for suffix in [config.common_suffix] + aslist(config.common_suffix_alt):
        if domain.endswith(suffix):
            domain = domain[:-len(suffix)]
            break
    else:
        raise exc.AddressException('Unknown domain: ' + domain)
    path = '/'.join(reversed(domain.split('.')))
    project, mount_point = h.find_project('/' + path)
    if project is None:
        raise exc.AddressException('Unknown project: ' + domain)
    if len(mount_point) != 1:
        raise exc.AddressException('Unknown tool: ' + domain)
    with h.push_config(c, project=project):
        app = project.app_instance(mount_point[0])
        if not app:
            raise exc.AddressException('Unknown tool: ' + domain)
    return userpart, project, app


def parse_message(data):
    # Parse the email to its constituent parts

    # https://bugs.python.org/issue25545 says
    # > A unicode string has no RFC defintion as an email, so things do not work right...
    # > You do have to conditionalize your 2/3 code to use the bytes parser and generator if you are dealing with 8-bit
    # > messages. There's just no way around that.
    # works the same as BytesFeedParser, and better than non-"Bytes" parsers for some messages
    parser = email.parser.BytesParser()
    msg = parser.parsebytes(data.encode('utf-8'))
    # Extract relevant data
    result = {}
    result['multipart'] = multipart = msg.is_multipart()
    # dict(msg) intentionally retains the longstanding, first-header-wins view
    # used by message handlers.  Sender authentication needs multiplicity so
    # that duplicate From or Authentication-Results fields fail closed.
    raw_headers = list(msg.raw_items())
    result['from_headers'] = [
        value for name, value in raw_headers if name.casefold() == 'from']
    result['authentication_results'] = [
        value for name, value in raw_headers
        if name.casefold() == 'authentication-results']
    result['headers'] = dict(msg)
    result['message_id'] = _parse_message_id(msg.get('Message-ID'))
    result['in_reply_to'] = _parse_message_id(msg.get('In-Reply-To'))
    result['references'] = _parse_message_id(msg.get('References'))
    if result['message_id'] == []:
        result['message_id'] = h.gen_message_id()
    else:
        result['message_id'] = result['message_id'][0]
    if multipart:
        result['parts'] = []
        for part in msg.walk():
            dpart = dict(
                headers=dict(part),
                message_id=result['message_id'],
                in_reply_to=result['in_reply_to'],
                references=result['references'],
                content_type=part.get_content_type(),
                filename=part.get_filename(None),
                payload=part.get_payload(decode=True))
            # payload is sometimes already unicode (due to being saved in mongo?)
            if part.get_content_maintype() == 'text':
                dpart['payload'] = six.ensure_text(dpart['payload'])
            result['parts'].append(dpart)
    else:
        result['payload'] = msg.get_payload(decode=True)
        # payload is sometimes already unicode (due to being saved in mongo?)
        if msg.get_content_maintype() == 'text':
            result['payload'] = six.ensure_text(result['payload'])

    return result


class SenderAuthenticationError(ValueError):

    def __init__(self, reason):
        self.reason = reason
        super().__init__(reason)


def _unfold_sender_authentication_header(value, max_octets):
    if not isinstance(value, str):
        raise SenderAuthenticationError('header_type')
    try:
        if len(value.encode('utf-8')) > max_octets:
            raise SenderAuthenticationError('header_too_long')
    except UnicodeEncodeError:
        raise SenderAuthenticationError('header_unicode')

    unfolded = []
    i = 0
    while i < len(value):
        char = value[i]
        if char in '\r\n':
            if char == '\r':
                if i + 1 >= len(value) or value[i + 1] != '\n':
                    raise SenderAuthenticationError('header_bad_fold')
                i += 2
            else:
                i += 1
            if i >= len(value) or value[i] not in ' \t':
                raise SenderAuthenticationError('header_bad_fold')
            while i < len(value) and value[i] in ' \t':
                i += 1
            unfolded.append(' ')
            continue
        codepoint = ord(char)
        if ((codepoint < 0x20 and char != '\t') or codepoint == 0x7f or
                0x80 <= codepoint <= 0x9f):
            raise SenderAuthenticationError('header_control')
        unfolded.append(char)
        i += 1

    value = ''.join(unfolded).strip(' \t')
    if not value:
        raise SenderAuthenticationError('header_empty')
    return value


def _split_authentication_results(value):
    clauses = []
    start = 0
    comment_depth = 0
    quoted = False
    escaped = False

    for i, char in enumerate(value):
        if escaped:
            escaped = False
            continue
        if quoted:
            if char == '\\':
                escaped = True
            elif char == '"':
                quoted = False
            continue
        if comment_depth:
            if char == '\\':
                escaped = True
            elif char == '(':
                comment_depth += 1
                if comment_depth > MAX_AUTHENTICATION_RESULTS_COMMENT_DEPTH:
                    raise SenderAuthenticationError('authentication_results_comment_depth')
            elif char == ')':
                comment_depth -= 1
            continue
        if char == '"':
            quoted = True
        elif char == '(':
            comment_depth = 1
        elif char == ')':
            raise SenderAuthenticationError('authentication_results_structure')
        elif char == ';':
            clause = value[start:i].strip(' \t')
            if not clause:
                raise SenderAuthenticationError('authentication_results_empty_clause')
            clauses.append(clause)
            if len(clauses) > MAX_AUTHENTICATION_RESULTS_CLAUSES:
                raise SenderAuthenticationError('authentication_results_too_many_clauses')
            start = i + 1

    if escaped or quoted or comment_depth:
        raise SenderAuthenticationError('authentication_results_structure')
    clause = value[start:].strip(' \t')
    if not clause:
        raise SenderAuthenticationError('authentication_results_empty_clause')
    clauses.append(clause)
    if len(clauses) > MAX_AUTHENTICATION_RESULTS_CLAUSES:
        raise SenderAuthenticationError('authentication_results_too_many_clauses')
    return clauses


def _normalize_sender_domain(domain):
    if (not isinstance(domain, str) or not domain or
            domain.startswith('.') or domain.endswith('.')):
        raise SenderAuthenticationError('domain_invalid')
    try:
        normalized = idna.encode(
            domain,
            uts46=True,  # Normalize Unicode and case variants before encoding.
            std3_rules=True,  # Request strict ASCII hostname character rules.
        ).decode('ascii').lower()
    except (idna.IDNAError, UnicodeError):
        raise SenderAuthenticationError('domain_invalid')
    labels = normalized.split('.')
    if (len(normalized) > 253 or '..' in normalized or
            any(not label or len(label) > 63 for label in labels)):
        raise SenderAuthenticationError('domain_invalid')
    return normalized


def _parse_exim_authentication_results(
        value, expected_authserv_id, from_domain):
    value = _unfold_sender_authentication_header(
        value, MAX_AUTHENTICATION_RESULTS_OCTETS)
    clauses = _split_authentication_results(value)
    authserv = clauses[0].split()
    # RFC 8601 treats an omitted header version as version 1.
    if authserv not in ([expected_authserv_id], [expected_authserv_id, '1']):
        raise SenderAuthenticationError('authserv_id')

    results = {'dmarc': [], 'spf': []}
    for clause in clauses[1:]:
        match = RE_TARGET_AUTHENTICATION_METHOD.match(clause)
        if match:
            results[match.group(1).lower()].append(clause)

    dmarc_results = results['dmarc']
    if len(dmarc_results) > 1:
        raise SenderAuthenticationError('dmarc_count')
    if dmarc_results:
        match = RE_DMARC_RESULT.fullmatch(dmarc_results[0])
        if not match:
            raise SenderAuthenticationError('dmarc_syntax')
        dmarc_result = match.group(1)
        if _normalize_sender_domain(match.group(2)) != from_domain:
            raise SenderAuthenticationError('from_domain_mismatch')
        if dmarc_result == 'pass':
            return 'dmarc'
        if dmarc_result != 'none':
            raise SenderAuthenticationError('dmarc_not_pass')

    # The trusted Exim ACL only runs SPF for public, unauthenticated mail.
    # Without a DMARC result, exact From/MAIL FROM domain alignment is the
    # intentionally conservative fallback; HELO-based SPF is not author proof.
    spf_results = results['spf']
    if not spf_results:
        raise SenderAuthenticationError('spf_missing')
    if len(spf_results) > 1:
        raise SenderAuthenticationError('spf_count')
    match = RE_SPF_RESULT.fullmatch(spf_results[0])
    if not match:
        raise SenderAuthenticationError('spf_syntax')
    if match.group(1) != 'pass':
        raise SenderAuthenticationError('spf_not_pass')
    if _normalize_sender_domain(match.group(2)) != from_domain:
        raise SenderAuthenticationError('from_domain_mismatch')
    return 'spf'


def _parse_from_mailbox(value):
    value = _unfold_sender_authentication_header(
        value, MAX_FROM_HEADER_OCTETS)
    parsed = email.parser.HeaderParser(policy=email.policy.default).parsestr(
        f'From: {value}\n\n')
    field = parsed['From']
    if field is None or field.defects:
        raise SenderAuthenticationError('from_defect')
    addresses = tuple(field.addresses)
    groups = tuple(field.groups)
    if (len(addresses) != 1 or
            any(group.display_name is not None for group in groups)):
        raise SenderAuthenticationError('from_mailbox_count')
    address = addresses[0]
    if not address.username or not address.domain:
        raise SenderAuthenticationError('from_invalid')
    mailbox = address.addr_spec
    if len(mailbox.encode('utf-8')) > 320:
        raise SenderAuthenticationError('from_too_long')
    return mailbox, _normalize_sender_domain(address.domain)


def _configured_trusted_relay_networks():
    values = aslist(config.get(
        'sender_authentication_trusted_relay_networks', ''))
    if not values:
        raise SenderAuthenticationError('trusted_relay_networks_missing')
    try:
        return [ipaddress.ip_network(value, strict=False) for value in values]
    except ValueError:
        raise SenderAuthenticationError('trusted_relay_networks_invalid')


def _peer_address(peer):
    if (not isinstance(peer, (tuple, list)) or len(peer) < 2 or
            not isinstance(peer[0], str)):
        raise SenderAuthenticationError('peer_invalid')
    try:
        address = ipaddress.ip_address(peer[0])
    except ValueError:
        raise SenderAuthenticationError('peer_invalid')
    if isinstance(address, ipaddress.IPv6Address) and address.ipv4_mapped:
        address = address.ipv4_mapped
    return address


def _authenticated_sender(peer, msg):
    from allura import model as M

    anonymous = M.User.anonymous()
    try:
        authserv_id = config.get('sender_authentication_authserv_id', '')
        if not isinstance(authserv_id, str):
            raise SenderAuthenticationError('authserv_id_config')
        authserv_id = authserv_id.strip()
        if (not authserv_id or
                _normalize_sender_domain(authserv_id) != authserv_id):
            raise SenderAuthenticationError('authserv_id_config')
        trusted_networks = _configured_trusted_relay_networks()
        peer_address = _peer_address(peer)
        if not any(
                peer_address.version == network.version and
                peer_address in network
                for network in trusted_networks):
            raise SenderAuthenticationError('untrusted_peer')
        if not isinstance(msg, dict):
            raise SenderAuthenticationError('message_missing')
        authentication_results = msg.get('authentication_results')
        from_headers = msg.get('from_headers')
        if (not isinstance(authentication_results, (list, tuple)) or
                len(authentication_results) != 1):
            raise SenderAuthenticationError('authentication_results_count')
        if (not isinstance(from_headers, (list, tuple)) or
                len(from_headers) != 1):
            raise SenderAuthenticationError('from_count')

        mailbox, from_domain = _parse_from_mailbox(from_headers[0])
        authentication_method = _parse_exim_authentication_results(
            authentication_results[0], authserv_id, from_domain)

        # DMARC or aligned SPF proves control of the From domain, not a
        # cryptographic per-mailbox identity. The exact confirmed address is
        # the application-side mapping for that domain-authenticated mailbox.
        owners = {}
        for address in M.EmailAddress.find({
                'email': mailbox,
                'confirmed': True,
        }):
            owner = address.claimed_by_user()
            if owner is not None:
                owners[owner._id] = owner
        if len(owners) != 1:
            raise SenderAuthenticationError('active_owner_count')
        return next(iter(owners.values())), f'{authentication_method}_pass'
    except SenderAuthenticationError as error:
        return anonymous, error.reason


def _legacy_identify_sender(email_address, headers):
    from allura import model as M
    # Dumb ID -- just look for email address claimed by a particular user
    addr = M.EmailAddress.get(email=email_address, confirmed=True)
    if addr and addr.claimed_by_user_id:
        return addr.claimed_by_user() or M.User.anonymous()
    from_address = headers.get('From', '').strip()
    if not from_address:
        return M.User.anonymous()
    addr = M.EmailAddress.get(email=from_address)
    if addr and addr.claimed_by_user_id:
        return addr.claimed_by_user() or M.User.anonymous()
    return M.User.anonymous()


def identify_sender(peer, email_address, headers, msg):
    from allura import model as M

    mode = config.get('sender_authentication_mode', 'disabled')
    if isinstance(mode, str):
        mode = mode.strip().lower()
    else:
        mode = ''

    if mode == 'disabled':
        return _legacy_identify_sender(email_address, headers)
    if mode not in {'monitor', 'enforce'}:
        log.error(
            'Invalid forgemail sender authentication mode %r; '
            'using anonymous sender', mode)
        return M.User.anonymous()

    if mode == 'monitor':
        legacy_user = _legacy_identify_sender(email_address, headers)
        try:
            verified_user, reason = _authenticated_sender(peer, msg)
            log.info(
                'Inbound sender authentication mode=monitor result=%s reason=%s '
                'peer=%s legacy_authenticated=%s identities_match=%s',
                not verified_user.is_anonymous(),
                reason,
                peer[0] if isinstance(peer, (tuple, list)) and peer else 'invalid',
                not legacy_user.is_anonymous(),
                legacy_user._id == verified_user._id,
            )
        except Exception:
            # Monitor is observational and must never change legacy delivery.
            log.exception(
                'Unexpected inbound sender authentication monitor error '
                'peer=%s',
                peer[0] if isinstance(peer, (tuple, list)) and peer else 'invalid')
        return legacy_user

    verified_user, reason = _authenticated_sender(peer, msg)
    log.info(
        'Inbound sender authentication mode=enforce result=%s reason=%s peer=%s',
        not verified_user.is_anonymous(),
        reason,
        peer[0] if isinstance(peer, (tuple, list)) and peer else 'invalid',
    )
    return verified_user


def encode_email_part(content, content_type):
    try:
        # simplest email - plain ascii
        encoded_content = content.encode('ascii')
        encoding = 'ascii'
        for line in encoded_content.splitlines():
            if len(line) > MAX_MAIL_LINE_OCTETS:
                # force base64 content-encoding to make lines shorter
                encoding = 'utf-8'
                break
    except Exception:
        # utf8 will get base64 encoded so we only do it if ascii fails
        encoded_content = content.encode('utf-8')
        encoding = 'utf-8'

    return MIMEText(encoded_content, content_type, encoding, policy=email_policy)


def make_multipart_message(*parts):
    msg = MIMEMultipart('related', policy=email_policy)
    msg.preamble = 'This is a multi-part message in MIME format.'
    alt = MIMEMultipart('alternative', policy=email_policy)
    msg.attach(alt)
    for part in parts:
        alt.attach(part)
    return msg


def _parse_message_id(msgid):
    if msgid is None:
        return []
    return [mo.group(1)
            for mo in RE_MESSAGE_ID.finditer(msgid)]


def _parse_smtp_addr(addr):
    addr = str(addr)
    addrs = _parse_message_id(addr)
    if addrs and addrs[0]:
        return addrs[0]
    if '@' in addr:
        return addr
    return g.noreply


def isvalid(addr):
    '''return True if addr is a (possibly) valid email address, false
    otherwise'''
    try:
        EMAIL_VALIDATOR.to_python(addr, None)
        return True
    except fev.Invalid:
        return False


class SMTPClient:

    def __init__(self):
        self._client = None

    def sendmail(
            self, addrs, fromaddr, reply_to, subject, message_id, in_reply_to, message: EmailMessage,
            sender=None, references=None, cc=None, to=None):
        if not addrs:
            return
        if to:
            message['To'] = AddrHeader(h.really_unicode(to))
        else:
            message['To'] = AddrHeader(reply_to)
        message['From'] = AddrHeader(fromaddr)
        message['Reply-To'] = AddrHeader(reply_to)
        message['Subject'] = Header(subject)
        message['Message-ID'] = Header('<' + message_id + '>')
        message['Date'] = email.utils.formatdate()
        if sender:
            message['Sender'] = AddrHeader(sender)
        if cc:
            message['CC'] = AddrHeader(cc)
            addrs.append(cc)
        if in_reply_to:
            if not isinstance(in_reply_to, str):
                raise TypeError('Only strings are supported now, not lists')
            message['In-Reply-To'] = Header('<%s>' % in_reply_to)
            if not references:
                message['References'] = message['In-Reply-To']
        if references:
            references = ['<%s>' % r for r in aslist(references)]
            message['References'] = Header(*references)

        # Kind of Hacky, but...
        #   Certain headers, like 'References' can become very long when sent via reply
        #   from deep inside a ticket thread. message.as_string allows you to pass a
        #   maxheaderlen which splits long lines for you to fit inside your exim constraints.
        #   HOWEVER, that flag doesn't take the header name length into account. So, this
        #   somewhat hacky code approximates the longest 'Header-Name: ' prefix and makes sure
        #   the line octet length takes that into account.
        longest_header_len = max(len(h[0]) for h in message._headers)
        max_header_len = MAX_MAIL_LINE_OCTETS - (2 + longest_header_len)

        content = message.as_string(maxheaderlen=max_header_len)
        smtp_addrs = list(map(_parse_smtp_addr, addrs))
        smtp_addrs = [a for a in smtp_addrs if isvalid(a)]
        if not smtp_addrs:
            log.warning('No valid addrs in %s, so not sending mail',
                        list(map(str, addrs)))
            return

        self.send_raw(config.return_path, smtp_addrs, content)

    def send_raw(self, addr_from, smtp_addrs, content):
        if not self._client:
            self._connect()
        try:
            self._client.sendmail(
                addr_from,
                smtp_addrs,
                content)
            need_retry = False
        except (smtplib.SMTPServerDisconnected, smtplib.SMTPConnectError) as e:
            log.info(f'will retry after getting this smtp error: {e!r}')
            need_retry = True
        except smtplib.SMTPResponseException as e:
            if 400 <= e.smtp_code < 500:  # 4__ is "Transient Negative"
                log.info(f'will retry after getting this smtp error: {e!r}')
                need_retry = True
            else:
                raise
        if need_retry:
            # maybe could sleep?  or if we're in a task, reschedule it somehow?
            self._connect()
            self._client.sendmail(
                addr_from,
                smtp_addrs,
                content)

    def _connect(self):
        log.info('connecting to SMTP server')
        if asbool(tg.config.get('smtp_ssl', False)):
            smtp_client = smtplib.SMTP_SSL(
                tg.config.get('smtp_server', 'localhost'),
                asint(tg.config.get('smtp_port', 25)),
                timeout=float(tg.config.get('smtp_timeout', 10)),
            )
        else:
            smtp_client = smtplib.SMTP(
                tg.config.get('smtp_server', 'localhost'),
                asint(tg.config.get('smtp_port', 465)),
                timeout=float(tg.config.get('smtp_timeout', 10)),
            )
        if tg.config.get('smtp_user', None):
            log.info('authenticating to SMTP server')
            smtp_client.login(tg.config['smtp_user'],
                              tg.config['smtp_password'])
        if asbool(tg.config.get('smtp_tls', False)):
            smtp_client.starttls()
        self._client = smtp_client
