#       Licensed to the Apache Software Foundation (ASF) under one
#       or more contributor license agreements.  See the NOTICE file
#       distributed with this work for additional information
#       regarding copyright ownership.  The ASF licenses this file
#       to you under the Apache License, Version 2.0 (the
#       "License"); you may not use this file except in compliance
#       with the License.  You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing,
#       software distributed under the License is distributed on an
#       "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#       KIND, either express or implied.  See the License for the
#       specific language governing permissions and limitations
#       under the License.

import re
import logging
import smtplib
import email.parser
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import header
from email.message import EmailMessage

import idna
import six
import tg
from paste.deploy.converters import asbool, asint, aslist
from formencode import validators as fev
from tg import tmpl_context as c
from tg import app_globals as g

from allura.lib.utils import ConfigProxy
from allura.lib import exceptions as exc
from allura.lib import helpers as h

log = logging.getLogger(__name__)

RE_MESSAGE_ID = re.compile(r'<(?:[^>]*/)?([^>]*)>')
config = ConfigProxy(
    common_suffix='forgemail.domain',
    common_suffix_alt='forgemail.domain.alternates',
    return_path='forgemail.return_path',
    sender_authentication_enabled='forgemail.sender_authentication.enabled',
    sender_authentication_header='forgemail.sender_authentication.header',
)
EMAIL_VALIDATOR = fev.Email(not_empty=True)

# http://www.jebriggs.com/blog/2010/07/smtp-maximum-line-lengths/
MAX_MAIL_LINE_OCTETS = 990
MAX_SENDER_AUTHENTICATION_HEADER_OCTETS = 1024
MAX_FROM_HEADER_OCTETS = 2 * 1024
SENDER_AUTHENTICATION_HEADER = 'X-SourceForge-Sender-Auth'
RE_HEADER_NAME = re.compile(r'(?a)\A[A-Za-z0-9][A-Za-z0-9-]{0,126}\Z')
RE_DMARC_SENDER_AUTHENTICATION = re.compile(
    r'(?a)\Av=1;[ \t]+dmarc=pass;[ \t]+'
    r'from-domain=([A-Za-z0-9.-]+)\Z')
RE_SPF_SENDER_AUTHENTICATION = re.compile(
    r'(?a)\Av=1;[ \t]+result=pass;[ \t]+method=spf-aligned;[ \t]+'
    r'from-domain=([A-Za-z0-9.-]+)\Z')

email_policy = email.policy.SMTP + email.policy.strict


def Header(text, *more_text) -> str:
    '''
    Helper to make sure we encode headers properly
    This used to return an email.header.Header instance
    But needs to be a plain str now that we're using email.policy.SMTP
    '''
    if isinstance(text, header.Header):
        return str(text)

    if not isinstance(text, str):
        raise TypeError('This must be unicode: %r' % text)

    hdr_text = text
    for m in more_text:
        if not isinstance(m, str):
            raise TypeError('This must be unicode: %r' % text)
        hdr_text += ' ' + m
    return hdr_text


def AddrHeader(fromaddr) -> str:
    '''Accepts any of:
        Header() instance
        foo@bar.com
        "Foo Bar" <foo@bar.com>
    '''
    if isinstance(fromaddr, str) and ' <' in fromaddr:
        name, addr = fromaddr.rsplit(' <', 1)
        addr = '<' + addr  # restore the char we just split off
        addrheader = Header(name, addr)
        if str(addrheader).startswith('=?'):  # encoding escape chars
            # then quoting the name is no longer necessary
            name = name.strip('"')
            addrheader = Header(name, addr)
    else:
        addrheader = Header(fromaddr)
    return addrheader


def is_autoreply(msg):
    '''Returns True, if message is an autoreply

    Detection based on suggestions from
    https://github.com/opennorth/multi_mail/wiki/Detecting-autoresponders
    '''
    h = msg['headers']
    return (
        h.get('Auto-Submitted') == 'auto-replied'
        or h.get('X-POST-MessageClass') == '9; Autoresponder'
        or h.get('Delivered-To') == 'Autoresponder'
        or h.get('X-FC-MachineGenerated') == 'true'
        or h.get('X-AutoReply-From') is not None
        or h.get('X-Autogenerated') in ['Forward', 'Group', 'Letter', 'Mirror', 'Redirect', 'Reply']
        or h.get('X-Precedence') == 'auto_reply'
        or h.get('Return-Path') == '<>'
    )


def parse_address(addr):
    userpart, domain = addr.split('@')
    # remove common domain suffix
    for suffix in [config.common_suffix] + aslist(config.common_suffix_alt):
        if domain.endswith(suffix):
            domain = domain[:-len(suffix)]
            break
    else:
        raise exc.AddressException('Unknown domain: ' + domain)
    path = '/'.join(reversed(domain.split('.')))
    project, mount_point = h.find_project('/' + path)
    if project is None:
        raise exc.AddressException('Unknown project: ' + domain)
    if len(mount_point) != 1:
        raise exc.AddressException('Unknown tool: ' + domain)
    with h.push_config(c, project=project):
        app = project.app_instance(mount_point[0])
        if not app:
            raise exc.AddressException('Unknown tool: ' + domain)
    return userpart, project, app


def parse_message(data):
    # Parse the email to its constituent parts

    # https://bugs.python.org/issue25545 says
    # > A unicode string has no RFC defintion as an email, so things do not work right...
    # > You do have to conditionalize your 2/3 code to use the bytes parser and generator if you are dealing with 8-bit
    # > messages. There's just no way around that.
    # works the same as BytesFeedParser, and better than non-"Bytes" parsers for some messages
    parser = email.parser.BytesParser()
    msg = parser.parsebytes(data.encode('utf-8'))
    # Extract relevant data
    result = {}
    result['multipart'] = multipart = msg.is_multipart()
    # dict(msg) intentionally retains the longstanding, first-header-wins view
    # used by message handlers. Sender authentication separately preserves all
    # From and configured authentication fields so duplicates fail closed.
    raw_headers = list(msg.raw_items())
    result['from_headers'] = [
        value for name, value in raw_headers if name.casefold() == 'from']
    authentication_header = config.get('sender_authentication_header', '')
    if isinstance(authentication_header, str):
        authentication_header = authentication_header.strip().casefold()
    else:
        authentication_header = ''
    result['sender_authentication_headers'] = [
        value for name, value in raw_headers
        if authentication_header and name.casefold() == authentication_header]
    result['headers'] = dict(msg)
    result['message_id'] = _parse_message_id(msg.get('Message-ID'))
    result['in_reply_to'] = _parse_message_id(msg.get('In-Reply-To'))
    result['references'] = _parse_message_id(msg.get('References'))
    if result['message_id'] == []:
        result['message_id'] = h.gen_message_id()
    else:
        result['message_id'] = result['message_id'][0]
    if multipart:
        result['parts'] = []
        for part in msg.walk():
            dpart = dict(
                headers=dict(part),
                message_id=result['message_id'],
                in_reply_to=result['in_reply_to'],
                references=result['references'],
                content_type=part.get_content_type(),
                filename=part.get_filename(None),
                payload=part.get_payload(decode=True))
            # payload is sometimes already unicode (due to being saved in mongo?)
            if part.get_content_maintype() == 'text':
                dpart['payload'] = six.ensure_text(dpart['payload'])
            result['parts'].append(dpart)
    else:
        result['payload'] = msg.get_payload(decode=True)
        # payload is sometimes already unicode (due to being saved in mongo?)
        if msg.get_content_maintype() == 'text':
            result['payload'] = six.ensure_text(result['payload'])

    return result


class SenderAuthenticationError(ValueError):

    def __init__(self, reason):
        self.reason = reason
        super().__init__(reason)


def _unfold_sender_authentication_header(value, max_octets):
    if not isinstance(value, str):
        raise SenderAuthenticationError('header_type')
    try:
        if len(value.encode('utf-8')) > max_octets:
            raise SenderAuthenticationError('header_too_long')
    except UnicodeEncodeError:
        raise SenderAuthenticationError('header_unicode')

    unfolded = []
    i = 0
    while i < len(value):
        char = value[i]
        if char in '\r\n':
            if char == '\r':
                if i + 1 >= len(value) or value[i + 1] != '\n':
                    raise SenderAuthenticationError('header_bad_fold')
                i += 2
            else:
                i += 1
            if i >= len(value) or value[i] not in ' \t':
                raise SenderAuthenticationError('header_bad_fold')
            while i < len(value) and value[i] in ' \t':
                i += 1
            unfolded.append(' ')
            continue
        codepoint = ord(char)
        if ((codepoint < 0x20 and char != '\t') or codepoint == 0x7f or
                0x80 <= codepoint <= 0x9f):
            raise SenderAuthenticationError('header_control')
        unfolded.append(char)
        i += 1

    value = ''.join(unfolded).strip(' \t')
    if not value:
        raise SenderAuthenticationError('header_empty')
    return value


def _normalize_sender_domain(domain):
    if (not isinstance(domain, str) or not domain or
            domain.startswith('.') or domain.endswith('.')):
        raise SenderAuthenticationError('domain_invalid')
    try:
        normalized = idna.encode(
            domain,
            uts46=True,
            transitional=False,
            std3_rules=True,
        ).decode('ascii').lower()
    except (idna.IDNAError, UnicodeError):
        raise SenderAuthenticationError('domain_invalid')
    labels = normalized.split('.')
    if (len(normalized) > 253 or '..' in normalized or
            any(not label or len(label) > 63 for label in labels)):
        raise SenderAuthenticationError('domain_invalid')
    return normalized


def _parse_sender_authentication_header(value, from_domain):
    value = _unfold_sender_authentication_header(
        value, MAX_SENDER_AUTHENTICATION_HEADER_OCTETS)
    for method, pattern in (
            ('dmarc', RE_DMARC_SENDER_AUTHENTICATION),
            ('spf_aligned', RE_SPF_SENDER_AUTHENTICATION)):
        match = pattern.fullmatch(value)
        if match:
            break
    else:
        raise SenderAuthenticationError('sender_authentication_syntax')

    if _normalize_sender_domain(match.group(1)) != from_domain:
        raise SenderAuthenticationError('from_domain_mismatch')
    return method


def _parse_from_mailbox(value):
    value = _unfold_sender_authentication_header(
        value, MAX_FROM_HEADER_OCTETS)
    parsed = email.parser.HeaderParser(policy=email.policy.default).parsestr(
        f'From: {value}\n\n')
    field = parsed['From']
    if field is None or field.defects:
        raise SenderAuthenticationError('from_defect')
    addresses = tuple(field.addresses)
    groups = tuple(field.groups)
    if (len(addresses) != 1 or
            any(group.display_name is not None for group in groups)):
        raise SenderAuthenticationError('from_mailbox_count')
    address = addresses[0]
    if not address.username or not address.domain:
        raise SenderAuthenticationError('from_invalid')
    mailbox = address.addr_spec
    if len(mailbox.encode('utf-8')) > 320:
        raise SenderAuthenticationError('from_too_long')
    return mailbox, _normalize_sender_domain(address.domain)


def _configured_sender_authentication_header():
    header_name = config.get('sender_authentication_header', '')
    if not isinstance(header_name, str):
        raise SenderAuthenticationError('sender_authentication_header_config')
    header_name = header_name.strip()
    # Exim strips this reserved name before adding its own attestation. Treat
    # the setting as a deployment-parity check; accepting an arbitrary name
    # would let an inbound copy under that other name bypass Exim's stripping.
    if (not RE_HEADER_NAME.fullmatch(header_name) or
            header_name.casefold() !=
            SENDER_AUTHENTICATION_HEADER.casefold()):
        raise SenderAuthenticationError('sender_authentication_header_config')
    return header_name


def _sender_authentication_enabled():
    value = config.get('sender_authentication_enabled', False)
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        value = value.strip().lower()
        if value in {'true', 'yes', 'on', '1'}:
            return True
        if value in {'false', 'no', 'off', '0'}:
            return False
    raise ValueError('invalid sender authentication enabled value')


def _authenticated_sender(msg):
    from allura import model as M

    anonymous = M.User.anonymous()
    try:
        _configured_sender_authentication_header()
        if not isinstance(msg, dict):
            raise SenderAuthenticationError('message_missing')
        authentication_headers = msg.get('sender_authentication_headers')
        from_headers = msg.get('from_headers')
        if (not isinstance(authentication_headers, (list, tuple)) or
                len(authentication_headers) != 1):
            raise SenderAuthenticationError('sender_authentication_header_count')
        if (not isinstance(from_headers, (list, tuple)) or
                len(from_headers) != 1):
            raise SenderAuthenticationError('from_count')

        mailbox, from_domain = _parse_from_mailbox(from_headers[0])
        authentication_method = _parse_sender_authentication_header(
            authentication_headers[0], from_domain)

        # DMARC or aligned SPF proves control of the From domain, not a
        # cryptographic per-mailbox identity. The exact confirmed address is
        # the application-side mapping for that domain-authenticated mailbox.
        owners = {}
        for address in M.EmailAddress.find({
                'email': mailbox,
                'confirmed': True,
        }):
            owner = address.claimed_by_user()
            if owner is not None:
                owners[owner._id] = owner
        if len(owners) != 1:
            raise SenderAuthenticationError('active_owner_count')
        return next(iter(owners.values())), f'{authentication_method}_pass'
    except SenderAuthenticationError as error:
        return anonymous, error.reason


def _legacy_identify_sender(email_address, headers):
    from allura import model as M
    # Dumb ID -- just look for email address claimed by a particular user
    addr = M.EmailAddress.get(email=email_address, confirmed=True)
    if addr and addr.claimed_by_user_id:
        return addr.claimed_by_user() or M.User.anonymous()
    from_address = headers.get('From', '').strip()
    if not from_address:
        return M.User.anonymous()
    addr = M.EmailAddress.get(email=from_address)
    if addr and addr.claimed_by_user_id:
        return addr.claimed_by_user() or M.User.anonymous()
    return M.User.anonymous()


def identify_sender(peer, email_address, headers, msg):
    from allura import model as M

    try:
        enabled = _sender_authentication_enabled()
    except ValueError:
        log.error(
            'Invalid forgemail sender authentication enabled value; '
            'using anonymous sender')
        return M.User.anonymous()

    if not enabled:
        return _legacy_identify_sender(email_address, headers)
    try:
        verified_user, reason = _authenticated_sender(msg)
    except Exception:
        log.exception('Unexpected inbound sender authentication error')
        return M.User.anonymous()
    peer_address = (
        peer[0]
        if isinstance(peer, (tuple, list)) and peer
        else 'invalid')
    log.info(
        'Inbound sender authentication enabled=true result=%s reason=%s '
        'peer=%s',
        not verified_user.is_anonymous(),
        reason,
        peer_address,
    )
    return verified_user


def encode_email_part(content, content_type):
    try:
        # simplest email - plain ascii
        encoded_content = content.encode('ascii')
        encoding = 'ascii'
        for line in encoded_content.splitlines():
            if len(line) > MAX_MAIL_LINE_OCTETS:
                # force base64 content-encoding to make lines shorter
                encoding = 'utf-8'
                break
    except Exception:
        # utf8 will get base64 encoded so we only do it if ascii fails
        encoded_content = content.encode('utf-8')
        encoding = 'utf-8'

    return MIMEText(encoded_content, content_type, encoding, policy=email_policy)


def make_multipart_message(*parts):
    msg = MIMEMultipart('related', policy=email_policy)
    msg.preamble = 'This is a multi-part message in MIME format.'
    alt = MIMEMultipart('alternative', policy=email_policy)
    msg.attach(alt)
    for part in parts:
        alt.attach(part)
    return msg


def _parse_message_id(msgid):
    if msgid is None:
        return []
    return [mo.group(1)
            for mo in RE_MESSAGE_ID.finditer(msgid)]


def _parse_smtp_addr(addr):
    addr = str(addr)
    addrs = _parse_message_id(addr)
    if addrs and addrs[0]:
        return addrs[0]
    if '@' in addr:
        return addr
    return g.noreply


def isvalid(addr):
    '''return True if addr is a (possibly) valid email address, false
    otherwise'''
    try:
        EMAIL_VALIDATOR.to_python(addr, None)
        return True
    except fev.Invalid:
        return False


class SMTPClient:

    def __init__(self):
        self._client = None

    def sendmail(
            self, addrs, fromaddr, reply_to, subject, message_id, in_reply_to, message: EmailMessage,
            sender=None, references=None, cc=None, to=None):
        if not addrs:
            return
        if to:
            message['To'] = AddrHeader(h.really_unicode(to))
        else:
            message['To'] = AddrHeader(reply_to)
        message['From'] = AddrHeader(fromaddr)
        message['Reply-To'] = AddrHeader(reply_to)
        message['Subject'] = Header(subject)
        message['Message-ID'] = Header('<' + message_id + '>')
        message['Date'] = email.utils.formatdate()
        if sender:
            message['Sender'] = AddrHeader(sender)
        if cc:
            message['CC'] = AddrHeader(cc)
            addrs.append(cc)
        if in_reply_to:
            if not isinstance(in_reply_to, str):
                raise TypeError('Only strings are supported now, not lists')
            message['In-Reply-To'] = Header('<%s>' % in_reply_to)
            if not references:
                message['References'] = message['In-Reply-To']
        if references:
            references = ['<%s>' % r for r in aslist(references)]
            message['References'] = Header(*references)

        # Kind of Hacky, but...
        #   Certain headers, like 'References' can become very long when sent via reply
        #   from deep inside a ticket thread. message.as_string allows you to pass a
        #   maxheaderlen which splits long lines for you to fit inside your exim constraints.
        #   HOWEVER, that flag doesn't take the header name length into account. So, this
        #   somewhat hacky code approximates the longest 'Header-Name: ' prefix and makes sure
        #   the line octet length takes that into account.
        longest_header_len = max(len(h[0]) for h in message._headers)
        max_header_len = MAX_MAIL_LINE_OCTETS - (2 + longest_header_len)

        content = message.as_string(maxheaderlen=max_header_len)
        smtp_addrs = list(map(_parse_smtp_addr, addrs))
        smtp_addrs = [a for a in smtp_addrs if isvalid(a)]
        if not smtp_addrs:
            log.warning('No valid addrs in %s, so not sending mail',
                        list(map(str, addrs)))
            return

        self.send_raw(config.return_path, smtp_addrs, content)

    def send_raw(self, addr_from, smtp_addrs, content):
        if not self._client:
            self._connect()
        try:
            self._client.sendmail(
                addr_from,
                smtp_addrs,
                content)
            need_retry = False
        except (smtplib.SMTPServerDisconnected, smtplib.SMTPConnectError) as e:
            log.info(f'will retry after getting this smtp error: {e!r}')
            need_retry = True
        except smtplib.SMTPResponseException as e:
            if 400 <= e.smtp_code < 500:  # 4__ is "Transient Negative"
                log.info(f'will retry after getting this smtp error: {e!r}')
                need_retry = True
            else:
                raise
        if need_retry:
            # maybe could sleep?  or if we're in a task, reschedule it somehow?
            self._connect()
            self._client.sendmail(
                addr_from,
                smtp_addrs,
                content)

    def _connect(self):
        log.info('connecting to SMTP server')
        if asbool(tg.config.get('smtp_ssl', False)):
            smtp_client = smtplib.SMTP_SSL(
                tg.config.get('smtp_server', 'localhost'),
                asint(tg.config.get('smtp_port', 25)),
                timeout=float(tg.config.get('smtp_timeout', 10)),
            )
        else:
            smtp_client = smtplib.SMTP(
                tg.config.get('smtp_server', 'localhost'),
                asint(tg.config.get('smtp_port', 465)),
                timeout=float(tg.config.get('smtp_timeout', 10)),
            )
        if tg.config.get('smtp_user', None):
            log.info('authenticating to SMTP server')
            smtp_client.login(tg.config['smtp_user'],
                              tg.config['smtp_password'])
        if asbool(tg.config.get('smtp_tls', False)):
            smtp_client.starttls()
        self._client = smtp_client
