#!/bin/bash

if [ "$TEST_MODULES"  == "" ]; then
    TEST_MODULES="\
    pyforge \
    ForgeDiscussion \
    ForgeGit \
    ForgeHg \
    ForgeMail \
    ForgeSVN \
    ForgeTracker \
    ForgeWiki \
    ."
fi

for module in $TEST_MODULES; do
    (
        echo "Running tests in module $module"
        cd $module
        nosetests $* || exit
    ) || exit
done

