#!/bin/bash

MODULES="\
    pyforge \
    ForgeDiscussion \
    ForgeGit \
    ForgeHg \
    ForgeMail \
    ForgeSVN \
    ForgeTracker \
    ForgeWiki"

for module in $MODULES; do
    (
        echo "====================="
        echo "Running tests in module $module"
        cd $module
        rm -r .test-data
        nosetests $* || exit
    ) || exit
done

